platform :ios, "11.0"
use_frameworks!
inhibit_all_warnings!

target 'LabCamp' do
    #For Reactive Programming
    pod 'RxSwift'
    pod 'RxCocoa'
    #pod 'RxGestures'
    #pod 'RxSwiftExt'
    #pod 'RxDataSources' 
end
