platform :ios, "11.0"
use_frameworks!
inhibit_all_warnings!

target 'LabChat' do
    #For Reactive Programming
 pod 'RxSwift'
 pod 'RxCocoa'
 #pod 'RxSwiftExt'
 #pod 'RxDataSources'
 #pod 'RxGestures'
    
    #For chat functionalities
  pod 'MessageKit'
    #Firebase is used as backend
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'MessageKit'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
              end
          end
      end
  end
end
